name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/typescript-action@releases/v1
      id: ts
    - name: print output
      run: echo "${{ steps.ts.outputs.time }}"
    - name: arbitrary shell output
      run: echo ::set-output name=action_fruit::strawberry
      id: shell
    - name: print shell
      run: echo "${{ steps.shell.outputs.action_fruit }}"
